### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by wang66624** [JnchinZ/Prototypical-Networks-for-image-classification#1]
![error](https://user-images.githubusercontent.com/81811919/164231817-2f7c3a3d-db2d-4c1c-8ffc-280e62241556.PNG)
Hi, I use my own dataset to run this code but have an error. Could you please give me some help?

**Comment by JnchinZ** [comment]
可能是你的保存图片路径和标签的csv索引文件没有'filename'这一列，建议参照[https://github.com/JnchinZ/Prototypical-Networks-for-image-classification/blob/main/omniglot/train.csv](https://github.com/JnchinZ/Prototypical-Networks-for-image-classification/blob/main/omniglot/train.csv)文件中那样的格式修改自己的csv索引文件。

**Comment by wang66624** [comment]
你好，他存的文件不是data/images_background/Alphabet_of_the_Magi/charactor01/*.png这样的吗，为什么csv文件里是data/Alphabet_of_the_Magi/charactor01/*.png,0,少了区分训练和测试的地址  ，我自己的数据集csv只能弄成data/train/1/*.jpg,怎样跟您的数据集csv存放匹配呢？
他的数据集：![image](https://user-images.githubusercontent.com/81811919/164243976-b460a98e-2ab9-4868-b07a-bde06fe71f79.png)
我的数据集：![image](https://user-images.githubusercontent.com/81811919/164244050-682616db-a83a-4076-81ea-7cec930d37d9.png)
出错：
![image](https://user-images.githubusercontent.com/81811919/164244340-338205c7-7ea8-4845-ab67-b1433ea040f1.png)

**Comment by JnchinZ** [comment]
csv文件只需要满足：1、仅两列数据；2、第一列是图片路径，列名是'filename'；第二列是标签，列名是'label'。这俩条件即可。至于图片路径到底是什么样的，只要能让数据集加载器找到文件就行，不用在意太多细节。

**Comment by wang66624** [comment]
好的谢谢，我再改改

**Comment by JnchinZ** [comment]
你可以自己写一个脚本来生成你自己csv索引文件：每行就是'图片的路径','label值'。训练数据保存到train.csv，验证数据保存到valid.csv等等。

**Comment by wang66624** [comment]
好的好的谢谢
